SurveyApp/Controllers/ParentTeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SurveyApp.Controllers
{
    public class ParentTeacherController : Controller
    {
        //
        // GET: /ParentTeacher/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ParentTeacherAddEdit(int? ID)
        {
            return View(ID);
        }

    }
}

SurveyApp/Controllers/StudyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SurveyApp.Controllers
{
    public class StudyController : Controller
    {
        //
        // GET: /Study/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult StudyAddEdit(int? id)
        {
            return View(id);
        }

    }
}

SurveyApp/Views/ParentTeacher/Index.cshtml
@{
    ViewBag.Title = "Parent/Teacher Management";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2 class="col-sm-11" style="margin: 0px;padding: 0px;">Parent/Teacher Management</h2>
<div class="col-sm-1">
@Html.ActionLink("Add", "ParentTeacherAddEdit", "ParentTeacher", new object { }, new { @class = "btn btn-default" }) 
    </div>
<style>
    .table-hover tbody tr{cursor:pointer;}
</style>
<table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>School</th>
        <th>Role</th>
        <th>Email</th>
        <th>Children</th>
        <th>Last Login</th>
        <th>Last Reminder</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <tr onclick="location.href = '@Url.Action("ParentTeacherAddEdit", "ParentTeacher", new { id = 1 })';">
        <td>Jack R.</td>
        <td>Oak International</td>
        <td>Teacher</td>
        <td>jack@yahoo.com</td>
        <td>5</td>
        <td class="text-success">01/18/2016</td>
        <td class="text-success">01/10/2016</td>
        <td><a href="#" class="btn-sm btn-info">Send Reminder</a></td>
      </tr>
       <tr onclick="location.href = '@Url.Action("ParentTeacherAddEdit", "ParentTeacher", new { id = 1 })';">
        <td>Fame Lamber</td>
        <td>-</td>
        <td>Parent</td>
        <td>fame@yahoo.com</td>
        <td>John Fame</td>
        <td class="text-danger">01/18/2014</td>
        <td class="text-success">01/10/2016</td>
        <td><a href="#" class="btn-sm btn-info">Send Reminder</a></td>
      </tr>      
        <tr onclick="location.href = '@Url.Action("ParentTeacherAddEdit", "ParentTeacher", new { id = 1 })';">
        <td>Anees Rona</td>
        <td>Oak International</td>
        <td>Teacher</td>
        <td>anees@yahoo.com</td>
        <td>5</td>
        <td class="text-success">01/18/2016</td>
        <td class="text-success">01/10/2016</td>
        <td><a href="#" class="btn-sm btn-info">Send Reminder</a></td>
      </tr>
       <tr onclick="location.href = '@Url.Action("ParentTeacherAddEdit", "ParentTeacher", new { id = 1 })';">
        <td>Jade Lamber</td>
        <td>-</td>
        <td>Parent</td>
        <td>jade@yahoo.com</td>
        <td>John Fame</td>
        <td class="text-danger">01/18/2014</td>
        <td class="text-success">01/10/2016</td>
        <td><a href="#" class="btn-sm btn-info">Send Reminder</a></td>
      </tr>

    </tbody>
  </table>

SurveyApp/Views/ParentTeacher/ParentTeacherAddEdit.cshtml
@{
    ViewBag.Title = "Parent/Teacher Information Editor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><a href="javascript:void(0);" id="back" onclick="history.go(-1);"></a> &nbsp;Parent/Teacher Information Editor</h2>

<style>
    ._panel { background: #fafafa; border: solid 1px #cccccc; padding: 10px; border-radius: 6px; }
</style>
<br />
<form class="form-horizontal" role="form">
            <div class="form-group">
        <label class="control-label col-sm-2" for="teacher">Study:</label>
        <div class="col-sm-10">
            <label><input type="checkbox" name="Teacher" /> Study A</label>
            <label><input type="checkbox" name="Teacher" /> Study B</label>
            <label><input type="checkbox" name="Teacher" /> Study C</label>
            <label><input type="checkbox" name="Teacher" /> Study D</label>
            <label><input type="checkbox" name="Teacher" /> Study E</label>
            @Html.ActionLink("Add Study", "StudyAddEdit", "Study", new object { }, new { @class = "btn btn-link" }) 
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2">Parent/Teacher Name</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" id="parent" placeholder="Parent/Teacher Name">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="gender">Role:</label>
        <div class="col-sm-4">
            <div class="radio-inline"><label><input type="radio" name="optradio" onclick="$('.divSchool').hide();">Parent</label></div>
            <div class="radio-inline"><label><input type="radio" name="optradio" onclick="$('.divSchool').show();">Teacher</label></div>
        </div>
    </div>
    <div class="form-group divSchool" style="display:none;">
        <label class="control-label col-sm-2" for="school">School:</label>
        <div class="col-sm-4">
            <select id="school" class="form-control"><option>Choose School</option><option>School A</option><option>School B</option><option>School C</option><option>School D</option></select>
            <a href="javascript:void(0);" class="btn btn-link" onclick="$('#addSchool').slideDown();">Add School</a>
        </div>    
        <div id="addSchool" class="_panel col-sm-12" style="display:none;">

        <div class="form-group">
            <label class="control-label col-sm-2">School Name</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="parent" placeholder="School Name">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2"> </label>
            <div class="col-sm-offset-2 col-sm-4">
                <button type="submit" class="btn btn-default">Add School</button>
                <button type="submit" class="btn btn-default" onclick="$('#addSchool').slideUp();">Cancel</button>
            </div>
        </div>
    </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="gender">Email:</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" id="parent" placeholder="Email">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="parent">Password:</label>
        <div class="col-sm-4">

            <input type="password" class="form-control" id="parent" placeholder="Password">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="parent">Confirm Password:</label>
        <div class="col-sm-4">

            <input type="password" class="form-control" id="parent" placeholder="Confirm Password">
        </div>
    </div>

  
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-4">
            <button type="submit" class="btn btn-default">Save Information</button>
        </div>
    </div>
</form>