SurveyApp/Controllers/ChildController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SurveyApp.Controllers
{
    public class ChildController : Controller
    {
        //
        // GET: /Child/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ChildAddEdit(int? id)
        {
            return View(id);
        }
    }
}

SurveyApp/Controllers/SchoolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SurveyApp.Controllers
{
    public class SchoolController : Controller
    {
        //
        // GET: /School/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SchoolAddEdit(int? ID)
        {
            return View(ID);
        }
    }
}

SurveyApp/Controllers/StudyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SurveyApp.Controllers
{
    public class StudyController : Controller
    {
        //
        // GET: /Study/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult StudyAddEdit(int? id)
        {
            return View(id);
        }

    }
}

SurveyApp/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SurveyApp.Controllers
{
    public class SurveyController : Controller
    {
        //
        // GET: /Survey/

        public ActionResult Index()
        {
            System.Data.DataSet ds = SurveyApp.DataHelper.SurveyGetAll();
            return View(ds);
        }
        public ActionResult Survey(int? surveyID)
        {
            return View(surveyID);
        }

    }
}

SurveyApp/Views/Shared/_AdminMenu.cshtml
 
@*@Html.ActionLink(dr["Title"].ToString(), "Survey",null, new { id = dr["ID"].ToString() },ew with {.class = "tab" })*@
@{
    var c = ViewContext.RouteData.Values["Controller"].ToString();
}
<div class="list-group small">
    @Html.ActionLink("Dashboard", "Index", "Home", new object { }, new { @class = "list-group-item" + (c == "Home" ? " active" : "") }) 
    @Html.ActionLink("Survey Manager", "Index", "Survey", new object { }, new { @class = "list-group-item" + (c == "Survey" ? " active" : "") }) 
    @Html.ActionLink("Parent/Teacher Manager", "Index", "ParentTeacher", new object { }, new { @class = "list-group-item" + (c == "ParentTeacher" ? " active" : "") }) 
    @Html.ActionLink("Child Manager", "Index", "Child", new object { }, new { @class = "list-group-item" + (c == "Child" ? " active" : "") }) 
    @Html.ActionLink("School Manager", "Index", "School", new object { }, new { @class = "list-group-item" + (c == "School" ? " active" : "") }) 
    @Html.ActionLink("Study Manager", "Index", "Study", new object { }, new { @class = "list-group-item" + (c == "Study" ? " active" : "") }) 
    @Html.ActionLink("Schedule Manager", "Index", "Schedule", new object { }, new { @class = "list-group-item" + (c == "Schedule" ? " active" : "") })  
</div>

SurveyApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/bootstrap/css/bootstrap-theme.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-2.2.0.min.js"></script>
    <script src="~/bootstrap/js/bootstrap.js"></script>
    <style>
        .form-group { margin-bottom: 5px; }
        .btn-link  { color: #23527c; text-decoration: underline; background-color: transparent; }
    </style>
</head>
<body>
    <header>
        <div class="content-wrapper" style="overflow:auto;padding:10px;">
            <div class="float-left">
                <p class="site-title">
                    <a href="javascript:void(0);"><img src='~/Images/at3logo.png' /></a>
                </p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
        <div id="body">
             <div class="col-sm-2" style="margin-top:10px;">
        @{
            Html.RenderPartial("~/Views/Shared/_AdminMenu.cshtml");
        }
    </div>
    <div class="col-sm-10">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">


                @RenderBody()

            </section>
        </div>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - AT<sup>3</sup> Autism Translating To Treatments</p>
            </div>
        </div>
    </footer>


    @RenderSection("scripts", required: false)

</body>
</html>