SurveyApp/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SurveyApp.Controllers
{
    public class ScheduleController : Controller
    {
        //
        // GET: /Schedule/

        public ActionResult Index()
        {
            return View();
        }


    }
}

SurveyApp/Controllers/StudyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SurveyApp.Controllers
{
    public class StudyController : Controller
    {
        //
        // GET: /Study/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult StudyAddEdit(int? id)
        {
            return View(id);
        }

    }
}

SurveyApp/Views/Study/Index.cshtml
@{
    ViewBag.Title = "Study Management";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2 class="col-sm-11" style="margin: 0px;padding: 0px;">Study Management</h2>
<div class="col-sm-1">
@Html.ActionLink("Add Study", "StudyAddEdit", "Study", new object { }, new { @class = "btn btn-default" }) 
</div>
<style>
    .table-hover tbody tr{cursor:pointer;}
</style>
<table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Study</th>
        <th>Survey(s)</th>
        <th>Student(s)</th>
        <th>Teacher(s)</th>
        <th>Parent(s)</th>
        <th>Completion</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <tr onclick="location.href = '@Url.Action("StudyAddEdit", "Study", new { id = 1 })';">
        <td>Temp Study 1</td>
        <td>5</td>
        <td>100</td>
        <td>12</td>
        <td>100</td>
        <td>40%</td>
        <td class="text-success">Active</td>
      </tr>
      <tr onclick="location.href = '@Url.Action("StudyAddEdit", "Study", new { id = 1 })';">
        <td>Temp Study 2</td>
        <td>8</td>
        <td>10</td>
        <td>1</td>
        <td>10</td>
        <td>20%</td>
        <td class="text-success">Active</td>
      </tr>
      <tr onclick="location.href = '@Url.Action("StudyAddEdit", "Study", new { id = 1 })';">
        <td>Temp Study 3</td>
        <td>8</td>
        <td>10</td>
        <td>1</td>
        <td>10</td>
        <td>20%</td>
        <td class="text-danger">Inactive</td>
      </tr>
        <tr onclick="location.href = '@Url.Action("StudyAddEdit", "Study", new { id = 1 })';">
        <td>Temp Study 5</td>
        <td>5</td>
        <td>100</td>
        <td>12</td>
        <td>100</td>
        <td>40%</td>
        <td class="text-success">Active</td>
      </tr>
      <tr onclick="location.href = '@Url.Action("StudyAddEdit", "Study", new { id = 1 })';">
        <td>Temp Study 6</td>
        <td>8</td>
        <td>10</td>
        <td>1</td>
        <td>10</td>
        <td>100%</td>
        <td class="text-success">Completed</td>
      </tr>
      <tr onclick="location.href = '@Url.Action("StudyAddEdit", "Study", new { id = 1 })';">
        <td>Temp Study 7</td>
        <td>8</td>
        <td>10</td>
        <td>1</td>
        <td>10</td>
        <td>20%</td>
        <td class="text-danger">Inactive</td>
      </tr>
    </tbody>
  </table>

SurveyApp/Views/Study/StudyAddEdit.cshtml
@{
    ViewBag.Title = "Study Information Editor";
    Layout = "~/Views/Shared/_Layout.cshtml";
    System.Data.DataSet ds = SurveyApp.DataHelper.SurveyGetAll();
}

<h2><a href="javascript:void(0);" id="back" onclick="history.go(-1);"></a> &nbsp;Study Information Editor</h2>

<style>
    ._panel { background: #fafafa; border: solid 1px #cccccc; padding: 10px; border-radius: 6px; }
</style>
<br />
<form class="form-horizontal" role="form">


    <div class="form-group">
        <label class="control-label col-sm-2">Study:</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" id="parent" placeholder="Study Name">
        </div>        
        <label class="control-label col-sm-1">Status:</label>
        <div class="col-sm-2">
            <select class="form-control"><option>Active</option><option>Inactive</option><option>Completed</option></select>
        </div>
        <div class="col-sm-2">@Html.ActionLink("Add Schedule Template", "Index", "Schedule", new object { }, new { @class = "btn btn-link" }) </div>
    </div>
    
    <div class="col-sm-offset-2 col-sm-10">
    <table class="table table-striped table-hover">
    <thead>
      <tr class="small">
        <th>Survey</th>
        <th>Schedule For Parent</th>
        <th>Schedule For Teacher</th>

      </tr>
    </thead>
    <tbody>@foreach (System.Data.DataRow dr in ds.Tables[0].Rows)
                {
      <tr>
        <td><label class="col-sm-12"> <input type="checkbox" name="Teacher" />&nbsp;
                                        @dr["Title"].ToString()
                                    </label></td>
        <td><select class="form-control">
                                            <option>Choose Template</option>
                                            <option>Test Schedule 1</option>
                                            <option>Test Schedule 2</option>
                                            <option>Test Schedule 3</option>
                                        </select></td>
        <td> <select class="form-control"> 
                                            <option>Choose Template</option>
                                            <option>Test Schedule 1</option>
                                            <option>Test Schedule 2</option>
                                            <option>Test Schedule 3</option>
                                        </select></td>
      </tr>
    }
     </table>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-4">
            <button type="submit" class="btn btn-default">Save Information</button>
        </div>
    </div>
</form>